import React, { useState, useEffect, useCallback } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { 
  fetchBillDetail, 
  updateBill, 
  deleteBill, 
  createBillPaymentReceipt,
  updatePaymentReceipt,
  deletePaymentReceipt,
  fetchBillLogs
} from "../../services/billingService";
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { AlertDialog, AlertDialogAction, AlertDialogCancel, AlertDialogContent, AlertDialogDescription, AlertDialogFooter, AlertDialogHeader, AlertDialogTitle, AlertDialogTrigger } from '@/components/ui/alert-dialog';
import { Plus, Edit, Trash2, Save, X, DollarSign, User, FileText, History, Receipt, CheckCircle, List, Percent, Download, File, Calendar } from 'lucide-react';

// Simplified Components
const Message = ({ type, message, onClose }) => (
  <div className={`${type === 'success' ? 'bg-green-50 border-green-200 text-green-600' : 'bg-red-50 border-red-200 text-red-600'} border rounded-md p-4 mb-4 flex items-center justify-between`}>
    <div className="flex items-center">
      {type === 'success' ? <CheckCircle className="w-5 h-5 mr-2" /> : <X className="w-5 h-5 mr-2" />}
      <p>{message}</p>
    </div>
    <button onClick={onClose} className="hover:opacity-70"><X className="w-4 h-4" /></button>
  </div>
);

const FormInput = ({ label, required, error, ...props }) => (
  <div>
    <label className="block text-sm font-medium text-gray-700 mb-1">
      {label} {required && <span className="text-red-500">*</span>}
    </label>
    <input {...props} className={`w-full px-3 py-2 border rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500 ${error ? 'border-red-300' : 'border-gray-300'}`} />
    {error && <p className="text-red-500 text-xs mt-1">{error}</p>}
  </div>
);

const StatusBadge = ({ status, type = 'bill' }) => {
  const colors = type === 'bill' 
    ? { 'DRAFT': 'bg-gray-100 text-gray-800', 'SCHEDULED': 'bg-yellow-100 text-yellow-800', 'PUBLISHED': 'bg-green-100 text-green-800' }
    : { 'pending': 'bg-red-100 text-red-800', 'partial': 'bg-yellow-100 text-yellow-800', 'paid': 'bg-green-100 text-green-800', 'overdue': 'bg-red-100 text-red-800' };
  return <span className={`px-2 py-1 rounded-full text-xs font-medium ${colors[status] || 'bg-gray-100 text-gray-800'}`}>
    {type === 'payment' ? status.charAt(0).toUpperCase() + status.slice(1) : status}
  </span>;
};

const TabNav = ({ activeTab, setActiveTab, tabs }) => (
  <div className="border-b border-gray-200">
    <nav className="flex space-x-8">
      {tabs.map((tab) => (
        <button key={tab.id} onClick={() => setActiveTab(tab.id)} className={`py-2 px-1 border-b-2 font-medium text-sm flex items-center space-x-2 ${
          activeTab === tab.id ? 'border-blue-500 text-blue-600' : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
        }`}>
          <tab.icon className="w-4 h-4" />
          <span>{tab.label}</span>
        </button>
      ))}
    </nav>
  </div>
);

// Main Component
const StudentBillDetail = () => {
  const { id } = useParams();
  const navigate = useNavigate();
  
  // Consolidated State
  const [state, setState] = useState({
    bill: null,
    loading: true,
    message: null,
    activeTab: 'details',
    editingBill: false,
    editingDiscount: false,
    addingCharge: false,
    addingReceipt: false,
    editingChargeId: null,
    editingReceiptId: null,
    billForm: {},
    discountForm: {},
    customCharges: [],
    paymentReceipts: [],
    logs: [],
    newCharge: { charge_name: '', description: '', amount: '' },
    // receipt_number removed — auto-generated by the server
    newReceipt: { amount_paid: '', payment_method: 'cash', notes: '' },
    editFormData: {}
  });

  // Helper function to update state
  const updateState = (updates) => setState(prev => ({ ...prev, ...updates }));

  // Utilities
  const showMessage = useCallback((type, text) => {
    updateState({ message: { type, text } });
    setTimeout(() => updateState({ message: null }), 5000);
  }, []);

  const formatCurrency = (amount) => `GHS ${parseFloat(amount || 0).toFixed(2)}`;
  const formatDate = (dateString) => dateString ? new Date(dateString).toLocaleDateString() : '';
  const formatDateTime = (dateTimeString) => {
    if (!dateTimeString) return '';
    const date = new Date(dateTimeString);
    return `${date.toLocaleDateString()} ${date.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' })}`;
  };

  // Load Bill Data
  const loadBillDetail = useCallback(async () => {
    try {
      updateState({ loading: true });
      const response = await fetchBillDetail(id);
      const billData = response.data;
      
      const updates = {
        bill: billData,
        billForm: {
          discount_amount: billData.discount_amount || '0.00',
          status: billData.status || 'DRAFT',
          notes: billData.notes || '',
          due_date: billData.due_date || '',
          scheduled_date: billData.scheduled_date || ''
        },
        discountForm: {
          discount_amount: billData.discount_amount || '0.00',
          discount_reason: billData.discount_reason || '',
          discount_approved_by: billData.discount_approved_by || ''
        },
        customCharges: billData.custom_charges || [],
        paymentReceipts: billData.payment_receipts || []
      };
      
      try {
        const logsResponse = await fetchBillLogs(id);
        updates.logs = logsResponse.data || [];
      } catch {
        updates.logs = [];
      }
      
      updateState(updates);
    } catch {
      showMessage('error', 'Failed to load bill details');
    } finally {
      updateState({ loading: false });
    }
  }, [id, showMessage]);

  useEffect(() => { loadBillDetail(); }, [loadBillDetail]);

  // Bill Operations
  const handleBillUpdate = async () => {
    try {
      const updateData = {
        discount_amount: state.billForm.discount_amount,
        status: state.billForm.status,
        notes: state.billForm.notes || '',
        due_date: state.billForm.due_date || state.bill?.due_date
      };

      // Add scheduled_date if status is SCHEDULED
      if (state.billForm.status === 'SCHEDULED') {
        if (!state.billForm.scheduled_date) {
          showMessage('error', 'Scheduled date and time is required when status is SCHEDULED');
          return;
        }
        updateData.scheduled_date = state.billForm.scheduled_date;
      } else {
        updateData.scheduled_date = null;
      }

      await updateBill(id, updateData);
      await loadBillDetail();
      updateState({ editingBill: false });
      showMessage('success', 'Bill updated successfully!');
    } catch (err) {
      const errorData = err.response?.data;
      const errorMessage = errorData?.detail || errorData?.message || 'Failed to update bill';
      showMessage('error', errorMessage);
    }
  };

  const handleBillDelete = async () => {
    try {
      await deleteBill(id);
      showMessage('success', 'Bill deleted successfully!');
      setTimeout(() => navigate('/bills'), 1000);
    } catch {
      showMessage('error', 'Failed to delete bill');
    }
  };

  // PDF Download
  const handlePdfDownload = () => {
    if (state.bill?.pdf_url) {
      window.open(state.bill.pdf_url, '_blank');
    } else {
      showMessage('error', 'PDF not available for this bill');
    }
  };

  // Discount Operations
  const handleDiscountUpdate = async () => {
    try {
      const discountAmount = parseFloat(state.discountForm.discount_amount || 0);
      
      // Validation
      if (isNaN(discountAmount) || discountAmount < 0) {
        showMessage('error', 'Discount amount must be a valid positive number');
        return;
      }

      if (discountAmount > 0) {
        if (!state.discountForm.discount_reason?.trim()) {
          showMessage('error', 'Discount reason is required when applying a discount');
          return;
        }
        if (!state.discountForm.discount_approved_by?.trim()) {
          showMessage('error', 'Approved by is required when applying a discount');
          return;
        }
      }

      // Prepare update data
      const updateData = {
        discount_amount: discountAmount.toFixed(2),
        discount_reason: state.discountForm.discount_reason?.trim() || '',
        discount_approved_by: state.discountForm.discount_approved_by?.trim() || '',
        status: state.bill.status,
        notes: state.bill.notes || '',
        due_date: state.bill.due_date,
        scheduled_date: state.bill.scheduled_date
      };

      await updateBill(id, updateData);
      await loadBillDetail();
      updateState({ editingDiscount: false });
      showMessage('success', 'Discount updated successfully!');
      
    } catch (err) {
      let errorMessage = 'Failed to update discount';
      const errorData = err.response?.data;
      
      if (errorData) {
        if (typeof errorData === 'object') {
          const fieldErrors = Object.entries(errorData)
            .map(([field, messages]) => 
              `${field}: ${Array.isArray(messages) ? messages.join(', ') : messages}`
            )
            .join('; ');
          
          if (fieldErrors) {
            errorMessage = fieldErrors;
          } else if (errorData.detail) {
            errorMessage = errorData.detail;
          } else if (errorData.message) {
            errorMessage = errorData.message;
          }
        } else if (typeof errorData === 'string') {
          errorMessage = errorData;
        }
      }
      
      showMessage('error', errorMessage);
    }
  };

  // Charge Operations
  const handleChargeAdd = async () => {
    try {
      const { charge_name, description, amount } = state.newCharge;
      if (!charge_name.trim()) throw new Error('Charge name is required');
      if (isNaN(parseFloat(amount)) || parseFloat(amount) <= 0) throw new Error('Amount must be a valid positive number');

      const updateData = {
        discount_amount: state.bill.discount_amount || '0.00',
        status: state.bill.status,
        notes: state.bill.notes || '',
        due_date: state.bill.due_date,
        scheduled_date: state.bill.scheduled_date,
        custom_charges: [
          ...state.customCharges,
          {
            charge_name: charge_name.trim(),
            description: description.trim(),
            amount: parseFloat(amount).toFixed(2)
          }
        ]
      };

      await updateBill(id, updateData);
      await loadBillDetail();
      updateState({ 
        newCharge: { charge_name: '', description: '', amount: '' },
        addingCharge: false 
      });
      showMessage('success', 'Custom charge added successfully!');
    } catch (err) {
      showMessage('error', err.message || 'Failed to add custom charge');
    }
  };

  const handleChargeDelete = async (chargeId) => {
    try {
      const updateData = {
        discount_amount: state.bill.discount_amount || '0.00',
        status: state.bill.status,
        notes: state.bill.notes || '',
        due_date: state.bill.due_date,
        scheduled_date: state.bill.scheduled_date,
        custom_charges: state.customCharges.filter(charge => charge.id !== chargeId)
      };

      await updateBill(id, updateData);
      await loadBillDetail();
      showMessage('success', 'Custom charge deleted successfully!');
    } catch (err) {
      showMessage('error', 'Failed to delete custom charge');
    }
  };

  // Receipt Operations
  const handleReceiptAdd = async () => {
    try {
      const { amount_paid, payment_method, notes } = state.newReceipt;

      // Validate amount only — receipt_number is now auto-generated server-side
      if (isNaN(parseFloat(amount_paid)) || parseFloat(amount_paid) <= 0) {
        throw new Error('Amount paid must be a valid positive number');
      }

      const data = {
        amount_paid: parseFloat(amount_paid).toFixed(2),
        payment_method: payment_method || 'cash',
        notes: notes.trim(),
        student_bill: parseInt(id)
      };

      await createBillPaymentReceipt(id, data);
      await loadBillDetail();
      updateState({ 
        newReceipt: { amount_paid: '', payment_method: 'cash', notes: '' },
        addingReceipt: false 
      });
      showMessage('success', 'Payment receipt added successfully!');
    } catch (err) {
      const errorData = err.response?.data;
      const errorMessage = errorData?.detail || errorData?.message || err.message || 'Failed to add payment receipt';
      showMessage('error', errorMessage);
    }
  };

  const handleReceiptDelete = async (receiptId) => {
    try {
      await deletePaymentReceipt(receiptId);
      await loadBillDetail();
      showMessage('success', 'Payment receipt deleted successfully!');
    } catch (err) {
      showMessage('error', 'Failed to delete payment receipt');
    }
  };

  // Loading & Error States
  if (state.loading) return (
    <div className="flex items-center justify-center min-h-[400px]">
      <div className="text-center">
        <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mx-auto mb-4"></div>
        <p className="text-gray-600">Loading bill details...</p>
      </div>
    </div>
  );
  
  if (!state.bill) return (
    <div className="flex items-center justify-center min-h-[400px]">
      <p className="text-red-600">Bill not found</p>
    </div>
  );

  // Calculate Totals
  const billingItems = state.bill.billing_template?.billing_items || [];
  const totalBillingItems = billingItems.reduce((sum, item) => sum + parseFloat(item.amount || 0), 0);
  const totalCustomCharges = state.customCharges.reduce((sum, charge) => sum + parseFloat(charge.amount || 0), 0);
  const balanceDue = state.bill.total_outstanding || state.bill.balance_due || 0;

  const tabs = [
    { id: 'details', label: 'Bill Details', icon: FileText },
    { id: 'charges', label: 'Custom Charges', icon: Plus },
    { id: 'payments', label: 'Payment Receipts', icon: Receipt },
    { id: 'discount', label: 'Discount', icon: Percent },
    { id: 'logs', label: 'Activity Logs', icon: History }
  ];

  return (
    <div className="max-w-9xl mx-auto p-6 space-y-6">
      {/* Header */}
      <div className="flex justify-between items-start">
        <div>
          <h1 className="text-3xl font-bold text-gray-900">Bill Details</h1>
          <p className="text-gray-600">Bill #{state.bill.bill_number}</p>
        </div>
        <div className="flex space-x-2">
          {state.bill.pdf_url && (
            <Button onClick={handlePdfDownload} variant="outline" size="sm">
              <Download className="w-4 h-4 mr-2" />Download PDF
            </Button>
          )}
          <Button onClick={() => updateState({ editingBill: !state.editingBill })} variant="outline" size="sm">
            <Edit className="w-4 h-4 mr-2" />{state.editingBill ? 'Cancel' : 'Edit Bill'}
          </Button>
          <AlertDialog>
            <AlertDialogTrigger asChild>
              <Button variant="destructive" size="sm">
                <Trash2 className="w-4 h-4 mr-2" />Delete
              </Button>
            </AlertDialogTrigger>
            <AlertDialogContent>
              <AlertDialogHeader>
                <AlertDialogTitle>Delete Bill</AlertDialogTitle>
                <AlertDialogDescription>This action cannot be undone.</AlertDialogDescription>
              </AlertDialogHeader>
              <AlertDialogFooter>
                <AlertDialogCancel>Cancel</AlertDialogCancel>
                <AlertDialogAction onClick={handleBillDelete} className="bg-red-600 hover:bg-red-700">Delete</AlertDialogAction>
              </AlertDialogFooter>
            </AlertDialogContent>
          </AlertDialog>
        </div>
      </div>

      {state.message && <Message type={state.message.type} message={state.message.text} onClose={() => updateState({ message: null })} />}

      {state.bill.pdf_url && (
        <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 flex items-start">
          <File className="w-5 h-5 text-blue-600 mr-3 mt-0.5" />
          <div>
            <p className="text-sm font-medium text-blue-800">PDF Bill Available</p>
            <p className="text-sm text-blue-700 mt-1">Click "Download PDF" to view or download it.</p>
          </div>
        </div>
      )}

      <TabNav activeTab={state.activeTab} setActiveTab={(tab) => updateState({ activeTab: tab })} tabs={tabs} />

      {/* Details Tab */}
      {state.activeTab === 'details' && (
        <div className="space-y-6">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Card>
              <CardHeader><CardTitle className="flex items-center"><User className="w-5 h-5 mr-2" />Student Info</CardTitle></CardHeader>
              <CardContent className="space-y-3">
                <div><label className="text-sm font-medium text-gray-500">Name</label><p className="text-lg font-medium">{state.bill.first_name} {state.bill.last_name}</p></div>
                <div><label className="text-sm font-medium text-gray-500">Class & Term</label><p>{state.bill.billing_template?.class_name} - {state.bill.billing_template?.term}</p></div>
                <div><label className="text-sm font-medium text-gray-500">Academic Year</label><p>{state.bill.billing_template?.academic_year}</p></div>
                <div><label className="text-sm font-medium text-gray-500">Status</label><div className="flex space-x-2"><StatusBadge status={state.bill.status} /><StatusBadge status={state.bill.payment_status} type="payment" /></div></div>
              </CardContent>
            </Card>

            <Card>
              <CardHeader><CardTitle className="flex items-center"><DollarSign className="w-5 h-5 mr-2" />Summary</CardTitle></CardHeader>
              <CardContent className="space-y-3">
                <div className="flex justify-between"><span className="text-gray-600">Previous Arrears</span><span className="font-medium">{formatCurrency(state.bill.previous_arrears)}</span></div>
                <div className="flex justify-between"><span className="text-gray-600">Current Bill</span><span className="font-medium">{formatCurrency(state.bill.total_amount_due)}</span></div>
                <div className="flex justify-between"><span className="text-gray-600">Total Paid</span><span className="font-medium text-green-600">{formatCurrency(state.bill.total_paid)}</span></div>
                <div className="flex justify-between"><span className="text-gray-600">Discount</span><span className="font-medium text-blue-600">-{formatCurrency(state.bill.discount_amount)}</span></div>
                <hr />
                <div className="flex justify-between text-lg font-bold">
                  <span>Balance Due</span>
                  <span className={parseFloat(balanceDue) > 0 ? 'text-red-600' : 'text-green-600'}>{formatCurrency(balanceDue)}</span>
                </div>
              </CardContent>
            </Card>
          </div>

          <div className="grid grid-cols-1 lg:grid-cols-2 gap-6">
            <Card>
              <CardHeader><CardTitle className="flex items-center"><List className="w-5 h-5 mr-2" />Billing Items</CardTitle></CardHeader>
              <CardContent>
                {billingItems.length === 0 ? (
                  <p className="text-center py-4 text-gray-500">No items found</p>
                ) : (
                  <div className="space-y-3">
                    {billingItems.map((item) => (
                      <div key={item.id} className="flex justify-between items-start border-b pb-2">
                        <div><p className="font-medium">{item.item_name}</p><p className="text-sm text-gray-500">{item.category}</p></div>
                        <p className="font-medium">{formatCurrency(item.amount)}</p>
                      </div>
                    ))}
                    <div className="flex justify-between pt-2 font-bold"><span>Total</span><span>{formatCurrency(totalBillingItems)}</span></div>
                  </div>
                )}
              </CardContent>
            </Card>

            <Card>
              <CardHeader><CardTitle className="flex items-center"><Plus className="w-5 h-5 mr-2" />Custom Charges</CardTitle></CardHeader>
              <CardContent>
                {state.customCharges.length === 0 ? (
                  <p className="text-center py-4 text-gray-500">No charges added</p>
                ) : (
                  <div className="space-y-3">
                    {state.customCharges.map((charge) => (
                      <div key={charge.id} className="flex justify-between items-start border-b pb-2">
                        <div><p className="font-medium">{charge.charge_name}</p>{charge.description && <p className="text-sm text-gray-500">{charge.description}</p>}</div>
                        <p className="font-medium">{formatCurrency(charge.amount)}</p>
                      </div>
                    ))}
                    <div className="flex justify-between pt-2 font-bold"><span>Total</span><span>{formatCurrency(totalCustomCharges)}</span></div>
                  </div>
                )}
              </CardContent>
            </Card>
          </div>

          {state.editingBill && (
            <Card>
              <CardHeader><CardTitle>Edit Bill</CardTitle></CardHeader>
              <CardContent className="space-y-4">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <FormInput 
                    label="Discount" 
                    type="number" 
                    step="0.01" 
                    min="0" 
                    value={state.billForm.discount_amount} 
                    onChange={(e) => updateState({ billForm: {...state.billForm, discount_amount: e.target.value} })} 
                  />
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Status</label>
                    <select 
                      value={state.billForm.status} 
                      onChange={(e) => {
                        const newStatus = e.target.value;
                        updateState({ 
                          billForm: {
                            ...state.billForm, 
                            status: newStatus,
                            scheduled_date: newStatus !== 'SCHEDULED' ? '' : state.billForm.scheduled_date
                          } 
                        });
                      }} 
                      className="w-full px-3 py-2 border border-gray-300 rounded-md"
                    >
                      <option value="DRAFT">Draft</option>
                      <option value="SCHEDULED">Scheduled</option>
                      <option value="PUBLISHED">Published</option>
                    </select>
                  </div>
                </div>

                {state.billForm.status === 'SCHEDULED' && (
                  <div className="grid grid-cols-1 gap-4">
                    <FormInput 
                      label="Scheduled Date & Time" 
                      type="datetime-local" 
                      required
                      value={state.billForm.scheduled_date} 
                      onChange={(e) => updateState({ billForm: {...state.billForm, scheduled_date: e.target.value} })} 
                    />
                    <p className="text-xs text-gray-500 -mt-2">
                      This bill will be published automatically on the scheduled date and time
                    </p>
                  </div>
                )}

                <div className="grid grid-cols-1 gap-4">
                  <FormInput 
                    label="Due Date" 
                    type="date" 
                    value={state.billForm.due_date} 
                    onChange={(e) => updateState({ billForm: {...state.billForm, due_date: e.target.value} })} 
                  />
                </div>

                <div>
                  <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
                  <textarea 
                    rows="3" 
                    value={state.billForm.notes} 
                    onChange={(e) => updateState({ billForm: {...state.billForm, notes: e.target.value} })} 
                    className="w-full px-3 py-2 border border-gray-300 rounded-md" 
                    placeholder="Notes..." 
                  />
                </div>

                <div className="flex space-x-2">
                  <Button onClick={handleBillUpdate}>
                    <Save className="w-4 h-4 mr-2" />Save
                  </Button>
                  <Button variant="outline" onClick={() => updateState({ editingBill: false })}>
                    <X className="w-4 h-4 mr-2" />Cancel
                  </Button>
                </div>
              </CardContent>
            </Card>
          )}

          {/* Display scheduled info in view mode */}
          {!state.editingBill && state.bill.status === 'SCHEDULED' && state.bill.scheduled_date && (
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <Calendar className="w-5 h-5 mr-2" />
                  Scheduled Publication
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4">
                  <p className="text-sm font-medium text-yellow-800">Scheduled Date & Time</p>
                  <p className="text-lg font-semibold text-yellow-900 mt-1">
                    {formatDateTime(state.bill.scheduled_date)}
                  </p>
                  <p className="text-sm text-yellow-700 mt-2">
                    This bill will be automatically published on the scheduled date and time.
                  </p>
                </div>
              </CardContent>
            </Card>
          )}
        </div>
      )}

      {/* Charges Tab */}
      {state.activeTab === 'charges' && (
        <Card>
          <CardHeader><div className="flex justify-between items-center"><CardTitle>Custom Charges</CardTitle><Button onClick={() => updateState({ addingCharge: true })}><Plus className="w-4 h-4 mr-2" />Add</Button></div></CardHeader>
          <CardContent>
            {state.addingCharge && (
              <div className="bg-gray-50 p-4 rounded-lg mb-4">
                <h3 className="text-lg font-medium mb-4">Add Charge</h3>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <FormInput label="Name" required value={state.newCharge.charge_name} onChange={(e) => updateState({ newCharge: {...state.newCharge, charge_name: e.target.value} })} placeholder="Late Fee" />
                  <FormInput label="Amount" type="number" step="0.01" min="0" required value={state.newCharge.amount} onChange={(e) => updateState({ newCharge: {...state.newCharge, amount: e.target.value} })} placeholder="0.00" />
                </div>
                <div className="mt-4"><label className="block text-sm font-medium text-gray-700 mb-1">Description</label><textarea rows="2" value={state.newCharge.description} onChange={(e) => updateState({ newCharge: {...state.newCharge, description: e.target.value} })} className="w-full px-3 py-2 border border-gray-300 rounded-md" placeholder="Optional..." /></div>
                <div className="flex space-x-2 mt-4">
                  <Button onClick={handleChargeAdd}><Save className="w-4 h-4 mr-2" />Add</Button>
                  <Button variant="outline" onClick={() => { updateState({ addingCharge: false, newCharge: { charge_name: '', description: '', amount: '' } }); }}><X className="w-4 h-4 mr-2" />Cancel</Button>
                </div>
              </div>
            )}

            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Name</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Description</th>
                    <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Amount</th>
                    <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Actions</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {state.customCharges.length === 0 ? (
                    <tr>
                      <td colSpan="4" className="px-6 py-4 text-center text-gray-500">No charges added</td>
                    </tr>
                  ) : state.customCharges.map((charge) => (
                    <tr key={charge.id}>
                      <td className="px-6 py-4 text-sm">{charge.charge_name}</td>
                      <td className="px-6 py-4 text-sm text-gray-500">{charge.description || '-'}</td>
                      <td className="px-6 py-4 text-sm text-right">{formatCurrency(charge.amount)}</td>
                      <td className="px-6 py-4 text-sm text-right">
                        <AlertDialog>
                          <AlertDialogTrigger asChild>
                            <Button variant="destructive" size="sm"><Trash2 className="w-4 h-4" /></Button>
                          </AlertDialogTrigger>
                          <AlertDialogContent>
                            <AlertDialogHeader>
                              <AlertDialogTitle>Delete Charge</AlertDialogTitle>
                              <AlertDialogDescription>Delete "{charge.charge_name}"?</AlertDialogDescription>
                            </AlertDialogHeader>
                            <AlertDialogFooter>
                              <AlertDialogCancel>Cancel</AlertDialogCancel>
                              <AlertDialogAction onClick={() => handleChargeDelete(charge.id)} className="bg-red-600 hover:bg-red-700">Delete</AlertDialogAction>
                            </AlertDialogFooter>
                          </AlertDialogContent>
                        </AlertDialog>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Payments Tab */}
      {state.activeTab === 'payments' && (
        <Card>
          <CardHeader><div className="flex justify-between items-center"><CardTitle>Payment Receipts</CardTitle><Button onClick={() => updateState({ addingReceipt: true })}><Plus className="w-4 h-4 mr-2" />Add</Button></div></CardHeader>
          <CardContent>
            {state.addingReceipt && (
              <div className="bg-gray-50 p-4 rounded-lg mb-4">
                <h3 className="text-lg font-medium mb-4">Add Payment</h3>
                {/* Receipt number is auto-generated — no input needed */}
                <div className="bg-blue-50 border border-blue-200 rounded-md p-3 mb-4 flex items-center">
                  <Receipt className="w-4 h-4 text-blue-600 mr-2 flex-shrink-0" />
                  <p className="text-sm text-blue-700">
                    A unique receipt number will be automatically generated when this payment is saved.
                  </p>
                </div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <FormInput
                    label="Amount Paid"
                    type="number"
                    step="0.01"
                    min="0"
                    required
                    value={state.newReceipt.amount_paid}
                    onChange={(e) => updateState({ newReceipt: {...state.newReceipt, amount_paid: e.target.value} })}
                    placeholder="0.00"
                  />
                  <div>
                    <label className="block text-sm font-medium text-gray-700 mb-1">Payment Method</label>
                    <select
                      value={state.newReceipt.payment_method}
                      onChange={(e) => updateState({ newReceipt: {...state.newReceipt, payment_method: e.target.value} })}
                      className="w-full px-3 py-2 border border-gray-300 rounded-md"
                    >
                      <option value="cash">Cash</option>
                      <option value="bank_transfer">Bank Transfer</option>
                      <option value="mobile_money">Mobile Money</option>
                      <option value="cheque">Cheque</option>
                      <option value="other">Other</option>
                    </select>
                  </div>
                </div>
                <div className="mt-4">
                  <label className="block text-sm font-medium text-gray-700 mb-1">Notes</label>
                  <textarea
                    rows="2"
                    value={state.newReceipt.notes}
                    onChange={(e) => updateState({ newReceipt: {...state.newReceipt, notes: e.target.value} })}
                    className="w-full px-3 py-2 border border-gray-300 rounded-md"
                    placeholder="Optional..."
                  />
                </div>
                <div className="flex space-x-2 mt-4">
                  <Button onClick={handleReceiptAdd}><Save className="w-4 h-4 mr-2" />Add Payment</Button>
                  <Button variant="outline" onClick={() => { updateState({ addingReceipt: false, newReceipt: { amount_paid: '', payment_method: 'cash', notes: '' } }); }}><X className="w-4 h-4 mr-2" />Cancel</Button>
                </div>
              </div>
            )}

            <div className="overflow-x-auto">
              <table className="min-w-full divide-y divide-gray-200">
                <thead className="bg-gray-50">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Receipt #</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Amount</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Method</th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase">Date</th>
                    <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase">Actions</th>
                  </tr>
                </thead>
                <tbody className="bg-white divide-y divide-gray-200">
                  {state.paymentReceipts.length === 0 ? (
                    <tr>
                      <td colSpan="5" className="px-6 py-4 text-center text-gray-500">No payments recorded</td>
                    </tr>
                  ) : state.paymentReceipts.map((receipt) => (
                    <tr key={receipt.id}>
                      <td className="px-6 py-4 text-sm font-mono text-gray-700">{receipt.receipt_number}</td>
                      <td className="px-6 py-4 text-sm font-medium text-green-600">{formatCurrency(receipt.amount_paid)}</td>
                      <td className="px-6 py-4 text-sm text-gray-500">{receipt.payment_method.replace('_', ' ').replace(/\b\w/g, l => l.toUpperCase())}</td>
                      <td className="px-6 py-4 text-sm text-gray-500">{formatDate(receipt.payment_date)}</td>
                      <td className="px-6 py-4 text-sm text-right">
                        <AlertDialog>
                          <AlertDialogTrigger asChild>
                            <Button variant="destructive" size="sm"><Trash2 className="w-4 h-4" /></Button>
                          </AlertDialogTrigger>
                          <AlertDialogContent>
                            <AlertDialogHeader>
                              <AlertDialogTitle>Delete Receipt</AlertDialogTitle>
                              <AlertDialogDescription>Delete receipt "{receipt.receipt_number}"?</AlertDialogDescription>
                            </AlertDialogHeader>
                            <AlertDialogFooter>
                              <AlertDialogCancel>Cancel</AlertDialogCancel>
                              <AlertDialogAction onClick={() => handleReceiptDelete(receipt.id)} className="bg-red-600 hover:bg-red-700">Delete</AlertDialogAction>
                            </AlertDialogFooter>
                          </AlertDialogContent>
                        </AlertDialog>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            </div>

            <div className="mt-4 bg-gray-50 p-4 rounded-lg">
              <div className="grid grid-cols-1 md:grid-cols-3 gap-4 text-center">
                <div><p className="text-sm text-gray-600">Total Receipts</p><p className="text-lg font-medium">{state.paymentReceipts.length}</p></div>
                <div><p className="text-sm text-gray-600">Total Paid</p><p className="text-lg font-medium text-green-600">{formatCurrency(state.bill.total_paid)}</p></div>
                <div><p className="text-sm text-gray-600">Balance</p><p className={`text-lg font-medium ${parseFloat(balanceDue) > 0 ? 'text-red-600' : 'text-green-600'}`}>{formatCurrency(balanceDue)}</p></div>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Discount Tab */}
      {state.activeTab === 'discount' && (
        <Card>
          <CardHeader>
            <div className="flex justify-between items-center">
              <CardTitle className="flex items-center"><Percent className="w-5 h-5 mr-2" />Discount Information</CardTitle>
              {!state.editingDiscount && <Button onClick={() => updateState({ editingDiscount: true })} variant="outline" size="sm"><Edit className="w-4 h-4 mr-2" />Edit Discount</Button>}
            </div>
          </CardHeader>
          <CardContent>
            {!state.editingDiscount ? (
              <div className="space-y-6">
                <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                  <div className="bg-blue-50 border border-blue-200 rounded-lg p-4"><label className="text-sm font-medium text-gray-600">Discount Amount</label><p className="text-2xl font-bold text-blue-600 mt-1">{formatCurrency(state.bill.discount_amount)}</p></div>
                  <div className="bg-gray-50 border border-gray-200 rounded-lg p-4"><label className="text-sm font-medium text-gray-600">Amount After Discount</label><p className="text-2xl font-bold text-gray-800 mt-1">{formatCurrency((parseFloat(totalBillingItems) + parseFloat(totalCustomCharges) - parseFloat(state.bill.discount_amount)))}</p></div>
                </div>
                <div className="space-y-4">
                  <div className="border-b pb-3"><label className="text-sm font-medium text-gray-600">Discount Reason</label><p className="text-base text-gray-800 mt-1">{state.bill.discount_reason || <span className="text-gray-400 italic">No reason provided</span>}</p></div>
                  <div className="border-b pb-3"><label className="text-sm font-medium text-gray-600">Approved By</label><p className="text-base text-gray-800 mt-1">{state.bill.discount_approved_by || <span className="text-gray-400 italic">Not specified</span>}</p></div>
                </div>
                {parseFloat(state.bill.discount_amount) === 0 && (
                  <div className="bg-yellow-50 border border-yellow-200 rounded-lg p-4 flex items-start">
                    <Percent className="w-5 h-5 text-yellow-600 mr-3 mt-0.5" />
                    <div><p className="text-sm font-medium text-yellow-800">No Discount Applied</p><p className="text-sm text-yellow-700 mt-1">Click "Edit Discount" to apply a discount to this bill.</p></div>
                  </div>
                )}
              </div>
            ) : (
              <div className="space-y-4">
                <div className="bg-blue-50 border border-blue-200 rounded-lg p-4 mb-4"><p className="text-sm text-blue-800"><strong>Note:</strong> When applying a discount, you must provide both a reason and the name of the person who approved it.</p></div>
                <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
                  <FormInput label="Discount Amount" type="number" step="0.01" min="0" required={parseFloat(state.discountForm.discount_amount) > 0} value={state.discountForm.discount_amount} onChange={(e) => updateState({ discountForm: {...state.discountForm, discount_amount: e.target.value} })} placeholder="0.00" />
                  <FormInput label="Approved By" type="text" required={parseFloat(state.discountForm.discount_amount) > 0} value={state.discountForm.discount_approved_by} onChange={(e) => updateState({ discountForm: {...state.discountForm, discount_approved_by: e.target.value} })} placeholder="Enter approver's name" />
                </div>
                <div><label className="block text-sm font-medium text-gray-700 mb-1">Discount Reason {parseFloat(state.discountForm.discount_amount) > 0 && <span className="text-red-500">*</span>}</label><textarea rows="4" value={state.discountForm.discount_reason} onChange={(e) => updateState({ discountForm: {...state.discountForm, discount_reason: e.target.value} })} className="w-full px-3 py-2 border border-gray-300 rounded-md focus:outline-none focus:ring-2 focus:ring-blue-500" placeholder="Provide a detailed reason for the discount..." /></div>
                <div className="bg-gray-50 border border-gray-200 rounded-lg p-4">
                  <div className="grid grid-cols-2 gap-4 text-sm">
                    <div><span className="text-gray-600">Original Amount:</span><span className="font-medium ml-2">{formatCurrency(parseFloat(totalBillingItems) + parseFloat(totalCustomCharges))}</span></div>
                    <div><span className="text-gray-600">Amount After Discount:</span><span className="font-bold text-blue-600 ml-2">{formatCurrency(Math.max(0, (parseFloat(totalBillingItems) + parseFloat(totalCustomCharges) - parseFloat(state.discountForm.discount_amount || 0))))}</span></div>
                  </div>
                </div>
                <div className="flex space-x-2 pt-2">
                  <Button onClick={handleDiscountUpdate}><Save className="w-4 h-4 mr-2" />Save Discount</Button>
                  <Button variant="outline" onClick={() => { updateState({ editingDiscount: false, discountForm: { discount_amount: state.bill.discount_amount || '0.00', discount_reason: state.bill.discount_reason || '', discount_approved_by: state.bill.discount_approved_by || '' } }); }}><X className="w-4 h-4 mr-2" />Cancel</Button>
                </div>
              </div>
            )}
          </CardContent>
        </Card>
      )}

      {/* Logs Tab */}
      {state.activeTab === 'logs' && (
        <Card>
          <CardHeader><CardTitle className="flex items-center"><History className="w-5 h-5 mr-2" />Activity Logs</CardTitle></CardHeader>
          <CardContent>
            {state.logs.length === 0 ? (
              <div className="text-center py-8 text-gray-500"><History className="w-12 h-12 mx-auto mb-4 opacity-50" /><p>No activity logs found</p></div>
            ) : (
              <div className="space-y-4">
                {state.logs.map((log, index) => (
                  <div key={index} className="border border-gray-200 rounded-lg p-4">
                    <div className="flex justify-between items-start">
                      <div>
                        <div className="flex space-x-2 mb-2"><span className="text-sm font-medium">{log.user_first_name} {log.user_last_name}</span><span className="text-xs text-gray-500">({log.user_email})</span></div>
                        <div className="text-sm text-gray-700"><span className="font-medium">Changed {(log.field_name || '').replace(/_/g, ' ')}:</span><div className="mt-1 pl-4 border-l-2 border-gray-200">{log.old_value && <div className="text-red-600"><span className="text-xs text-gray-500">From:</span> {log.old_value}</div>}<div className="text-green-600"><span className="text-xs text-gray-500">To:</span> {log.new_value || '(empty)'}</div></div></div>
                      </div>
                      <div className="text-right text-xs text-gray-500"><div>{formatDate(log.timestamp)}</div><div className="text-gray-400">{new Date(log.timestamp).toLocaleTimeString()}</div></div>
                    </div>
                  </div>
                ))}
              </div>
            )}
          </CardContent>
        </Card>
      )}
    </div>
  );
};

export default StudentBillDetail;